# Generated by Django 3.2.1 on 2021-05-05 02:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('transactionId', models.UUIDField(default=uuid.UUID('6200bc31-173e-44cb-a578-dde808abc3b8'), editable=False, primary_key=True, serialize=False, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('interest', models.DecimalField(decimal_places=2, max_digits=5)),
                ('loanCode', models.UUIDField(blank=True, default=uuid.UUID('d58800c5-0899-4bb8-aef8-ac122cbf045a'), null=True)),
                ('loanDate', models.DateTimeField(auto_now_add=True)),
                ('loanDueDate', models.DateTimeField(blank=True)),
                ('customerId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
