# Generated by Django 3.2.1 on 2021-05-05 14:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('transactionId', models.UUIDField(default=uuid.uuid1, primary_key=True, serialize=False, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('interest', models.DecimalField(decimal_places=2, max_digits=10)),
                ('loanCode', models.UUIDField(blank=True, default=uuid.UUID('6563d679-7d6a-4954-b17f-f81b6e72bba5'), null=True)),
                ('loanDate', models.DateTimeField(auto_now_add=True)),
                ('loanDueDate', models.DateField()),
                ('customerId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
