# Generated by Django 3.2.1 on 2021-05-05 03:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0002_auto_20210505_0246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='loanCode',
            field=models.UUIDField(blank=True, default=uuid.UUID('02ad96a9-6843-4229-83e5-d387a6e258d3'), null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='loanDueDate',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='loan',
            name='transactionId',
            field=models.UUIDField(default=uuid.UUID('a24b843c-8a01-4a16-9ab7-ba840573374d'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
