# Generated by Django 3.2.1 on 2021-05-05 04:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0006_auto_20210505_0406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='loanCode',
            field=models.UUIDField(blank=True, default=uuid.UUID('dd4b74eb-2f73-468d-99a4-7f79d0251caf'), null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='transactionId',
            field=models.UUIDField(default=uuid.uuid1, primary_key=True, serialize=False, unique=True),
        ),
    ]
